name: Datalog tiny 
on:
  push:
    branches:
    - master

jobs:
   esp8622:
    runs-on: ubuntu-latest
   
    steps:
      - name: Install arduino-cli for esp8622
        run: |
          apt-get install curl git -y
          cd ~
          mkdir arduino-init 
          cd arduino-init 
          curl -L -o arduino-cli.tar.bz2 https://downloads.arduino.cc/arduino-cli/arduino-cli-latest-linux64.tar.bz2
          tar xjf arduino-cli.tar.bz2
          mv arduino-cli /usr/bin/arduino-cli
          arduino-cli core update-index --config-file arduino-cli.yaml
          ARDUINO_YAML=$(arduino-cli config init | awk '{ print $4 }')
          echo board_manager: >> $ARDUINO_YAML
          echo '  additional_urls:' >> $ARDUINO_YAML
          echo '      - http://arduino.esp8266.com/stable/package_esp8266com_index.json' >> $ARDUINO_YAML
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266
        
      - name: Clone datalog-tiny repo
        run: |
          echo " git clone" 
          cd ~
          git clone https://github.com/airalab/robonomics-client-cpp.git
          cd robonomics-client-cpp 
          ARDUINO_SKETCH=$(arduino-cli config dump | grep sketchbook_path | awk '{ print $2 }')
          mkdir $ARDUINO_SKETCH
          mv libraries/ $ARDUINO_SKETCH/
          cp rpcjsonc/rpcjsonc.ino $ARDUINO_SKETCH/rpcjsonc.ino
          cd ..
          rm -rf robonomics-client-cpp

      - name: Build 
        run: |
          ARDUINO_SKETCH=$(arduino-cli config dump | grep sketchbook_path | awk '{ print $2 }')
          cd $ARDUINO_SKETCH 
          /usr/bin/arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 rpcjsonc.ino
