name: Datalog tiny 
on:
  push:
    branches:
    - master

jobs:
  libtests:
    runs-on: ubuntu-latest
   
    steps:
      - name: Install g++
        run: |
          apt-get install curl git -y
          cd ~
        
      - name: Clone datalog-tiny repo
        run: |
          echo " git clone" 
          cd ~
          git clone https://github.com/airalab/robonomics-client-cpp.git
          #git clone https://github.com/yamukha/esp_extinsic.git

      - name: Install cryptopp from repo
        run: |
          git clone https://github.com/weidai11/cryptopp
          cd cryptopp
          make libcryptopp.a libcryptopp.so -j4
          make install PREFIX=/usr/local  -j4
          ldconfig

      - name: Build 
        run: |
          cd ~/robonomics-client-cpp/tests
          #cd  ~/esp_extinsic/tests
          g++ test_call.c -o test_call -DUNIT_TEST -L/usr/local/lib -lcryptopp
          #g++ test_call.c -o test_call -DUNIT_TEST -L/usr/local/lib -l:libcryptopp.a
          ./test_call 
